from abc import ABC, abstractmethod
from spotmicro.agent.input import Input

class Device(ABC):
    @abstractmethod
    def update(self) -> None:
        """
        Update the state of the (software) device, by refreshing the internally held input values
        """
        pass

    @abstractmethod
    def read(self) -> Input:
        """
        Read the input generated by device
        """
        pass

#TODO
class RandomController(Device):
    def __init__(self):
        pass

    def update(self) -> None:
        """
        Just a dummy for now
        """
        pass

    def read(self) -> Input:
        """
        Just a dummy for now
        """
        return Input(0.0, 0.0, 0.0)

class Joystick(Device):
    def __init__(self):
        raise NotImplementedError("Joystick device is not implemented yet")

class Keyboard(Device):
    def __init__(self):
        raise NotImplementedError("Keyboard device is not implemented yet")

class DeterministicController(Device):
    def __init__(self):
        raise NotImplementedError("DeterministicController device is not implemented yet")