from abc import ABC, abstractmethod
from spotmicro.agent.input import Input
import numpy as np

class Device(ABC):
    @abstractmethod
    def update(self) -> None:
        """
        Update the state of the (software) device, by refreshing the internally held input values
        """
        pass

    @abstractmethod
    def read(self) -> Input:
        """
        Read the input generated by device
        """
        pass

#TODO
class RandomController(Device):
    def __init__(self):
        self._input = Input()

    def update(self) -> None:
        """
        Update the internal state of the controller.
        May randomly change the input
        """
        pass

    def read(self) -> Input:
        """
        Obtain the current input to give to the agent
        """
        return self._input

class Joystick(Device):
    def __init__(self):
        raise NotImplementedError("Joystick device is not implemented yet")

class Keyboard(Device):
    def __init__(self):
        raise NotImplementedError("Keyboard device is not implemented yet")

class DeterministicController(Device):
    def __init__(self):
        raise NotImplementedError("DeterministicController device is not implemented yet")