from abc import ABC, abstractmethod
from src.spotmicro.agent.input import Input


class Device(ABC):
    @abstractmethod
    def update(self) -> None:
        """
        Update the state of the (software) device, by refreshing the internally held input values
        """
        pass

    @abstractmethod
    def read(self) -> Input:
        """
        Read (return) the input generated by device
        """
        pass

    @abstractmethod
    def reset(self) -> None:
        """
        Reset the device to its initial state. Called when resetting the environment
        """