from abc import ABC, abstractmethod
from spotmicro.agent.input import Input
import numpy as np

class Device(ABC):
    @abstractmethod
    def update(self) -> None:
        """
        Update the state of the (software) device, by refreshing the internally held input values
        """
        pass

    @abstractmethod
    def read(self) -> Input:
        """
        Read the input generated by device
        """
        pass

    @abstractmethod
    def reset(self) -> None:
        """
        Reset the device to its initial state. Called when resetting the environment
        """

class DeterministicController(Device):
    def __init__(self):
        raise NotImplementedError("DeterministicController device is not implemented yet")