from abc import ABC, abstractmethod
from spotmicro.agent.input import Input
import numpy as np

class Device(ABC):
    @abstractmethod
    def update(self) -> None:
        """
        Update the state of the (software) device, by refreshing the internally held input values
        """
        pass

    @abstractmethod
    def read(self) -> Input:
        """
        Read the input generated by device
        """
        pass

class DeterministicController(Device):
    def __init__(self):
        raise NotImplementedError("DeterministicController device is not implemented yet")